### ISSUE TITLE
Error 400 

### ISSUE THREAD

**Issue by TrigrD3** [davila7/code-gpt-docs#123]
OpenAI API Response was: Error 400: This model's maximum context length is 4097 tokens. However, you requested 5444 tokens (444 in the messages, 5000 in the completion). Please reduce the length of the messages or completion. More information about this error: https://www.codegpt.co/docs/tutorial-basics/api_errors

this happens when you set the max token setting above the "model's maximum context length is 4097 tokens" hence the "5000 in the completion" which mean when we're sending a request we automatically sending our context token (444 in the messages) + the max token setting.

![image](https://user-images.githubusercontent.com/55515446/232177474-a0459b9b-6d8a-4dd5-aad4-a9b99b2fb42c.png)

to fix this, just set the max token setting lower.

**Comment by Vuthric** [comment]
same here. I cleared chat out of desperation but didn't fix anything.

**Comment by Vuthric** [comment]
Update: 
A couple things to try.
1. CodeGPT settings only takes effect after a VSCode restart. The solution could be real. I can't validate though because I di
2. You can uninstall/reinstall CodeGPT extension to clear its cache, which worked for me. Or you can 
3. Delete C:\Users\[User]\AppData\Roaming\Code\User\globalStorage\state.vscdb and state.vscdb.backup

Note that 3) would delete a bunch of other cache like if you trust your current WSL, or your current layout etc.. so proceed with caution.

**Comment by chimpanstache** [comment]
On my side I'm getting this error
```
OpenAI API Response was: Error 400: This model's maximum context length is 16385 tokens. However, your messages resulted in 28811 tokens. Please reduce the length of the messages. 
```
I never had it before, and it's been several months that I'm using codeGPT.
The input was simply this:
`In go how to get the last item of a slice ?`
And here is how the extension is configured on my editor:
![Screenshot 2023-09-19 at 20 05 50](https://github.com/davila7/code-gpt-docs/assets/53328741/f46c14b0-1360-444e-b156-ecd2b8e940a2)

**Comment by chimpanstache** [comment]
Also impossible to join the discord group

**Comment by lilei105** [comment]
same here no matter how I try, a simple question like "what's the difference between next.js and react.js" results in a error 400:
OpenAI API Response was: Error 400: This model's maximum context length is 4097 tokens. However, your messages resulted in 21798 tokens. Please reduce the length of the messages. More information about this error: https://docs.codegpt.co/docs/tutorial-basics/api_errors

**Comment by lilei105** [comment]
> Update: A couple things to try.
> 
> 1. CodeGPT settings only takes effect after a VSCode restart. The solution could be real. I can't validate though because I did 2:
> 2. You can uninstall/reinstall CodeGPT extension to clear its cache, which worked for me. Or you can
> 3. Delete C:\Users[User]\AppData\Roaming\Code\User\globalStorage\state.vscdb and state.vscdb.backup
> 
> Note that 3) would delete a bunch of other cached settings like if you trust your current WSL, or your current layout etc.. I don't use VSC enough to know the exact damage. So proceed with caution.

3 worked for me

**Comment by chimpanstache** [comment]
> > Update: A couple things to try.
> > 
> > 1. CodeGPT settings only takes effect after a VSCode restart. The solution could be real. I can't validate though because I did 2:
> > 2. You can uninstall/reinstall CodeGPT extension to clear its cache, which worked for me. Or you can
> > 3. Delete C:\Users[User]\AppData\Roaming\Code\User\globalStorage\state.vscdb and state.vscdb.backup
> > 
> > Note that 3) would delete a bunch of other cached settings like if you trust your current WSL, or your current layout etc.. I don't use VSC enough to know the exact damage. So proceed with caution.
> 
> 3 worked for me

Same here

**Comment by PilarHidalgo** [comment]
Yes, you're correct. Each model has a maximum context length, which is the total number of tokens that can be processed in a single request. This includes both the input message tokens and the tokens generated in the response. In your case, the model's maximum context length is 4097 tokens, but the request included 5444 tokens (444 from the messages and 5000 from the completion). To resolve this, you need to reduce the length of the messages or the completion so that the total number of tokens does not exceed the model's maximum context length.
