### ISSUE TITLE
Code theme is difficult to use in light mode

### ISSUE THREAD

**Issue by LouisIngenthron** [davila7/code-gpt-docs#126]
![image](https://user-images.githubusercontent.com/31388928/232217562-dedf49a8-9c38-4e62-9d53-c7f156e64cf5.png)
See image.  In standard light mode settings for VS Code, the code blocks for Code GPT are dark red text over a black background.  They're essentially unreadable.

Even when trying to get it to fix this itself, it seems to be unable to do so:
![image](https://user-images.githubusercontent.com/31388928/232217452-644b8345-d8b3-47a9-bc43-54f964b844ae.png)

**Comment by richlysakowski** [comment]
Ditto here.  The code is not styled correctly.  Some of it is invisible.  

![image](https://user-images.githubusercontent.com/9345711/235289846-e579f456-aa57-41ef-ac11-06a5f34cea48.png)

But the ACTUAL CODE is shown when I highlight it with the mouse...

![image](https://user-images.githubusercontent.com/9345711/235289877-0bebb4e8-d195-41a1-8b38-593349bb8424.png)

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're having trouble with the visibility of the code blocks in CodeGPT on VS Code. This could be due to a conflict between the theme settings of your VS Code and the CodeGPT extension.

You can try changing the theme of your VS Code to see if it resolves the issue. To do this, go to File > Preferences > Color Theme and select a different theme.
