### ISSUE TITLE
Sidebar wont clear chat

### ISSUE THREAD

**Issue by DzT13** [davila7/code-gpt-docs#134]
I have a problem, the extension in the sidebar won't delete chat history. A button appears like in the screenshot below, and the button doesn't want to disappear. I've reinstalled the extension several times, but the problem persists.

![image](https://user-images.githubusercontent.com/76884559/234933826-321f9438-8705-458a-98e4-aa0ddf0e931b.png)

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're having trouble with the chat history in the CodeGPT extension. This could be due to a few reasons. Here are some steps you can try:

Ensure that you're using the latest version of the CodeGPT extension. You can check this in the Extensions tab in VSCode.
Try clearing the cache of your VSCode. You can do this by going to File > Invalidate Caches / Restart.
If the problem persists, you might want to consider resetting your VSCode settings to default.
