### ISSUE TITLE
chat window does not load, constant loading icon appears only.

### ISSUE THREAD

**Issue by jocot** [davila7/code-gpt-docs#203]
First time trying this extension.

I selected Ollama which I have running but even with ChatGPT nothing seems to load, have tried restarting vscode after changing settings to no avail.

VSCode info:
Version: 1.80.2
Release: 23209
Commit: ad2ce925243280c8cd1054a2b27734e2b2e839c5
Date: 2023-07-28T18:27:49.392Z
Electron: 22.3.14
ElectronBuildId: undefined
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.6.0-61.rog.fc38.x86_64

**Comment by reserschnell** [comment]
I have the same issue, nothing is loading in the chat window. It simply keeps black.
Version: 1.86.0 (user setup)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:28:19.990Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by reserschnell** [comment]
Could it be that it's related to some restrictions from the company. The issue happens only with my company pc, not with my privat one.

**Comment by rmeissn** [comment]
I got a personal laptop and Code GPT only shows a black window. No text, no error message, nothing.
I'm using it on
Version: 1.85.2
Release: 24019
Commit: c8a36a69377856369f139f39ee56dd3838130fbf
Date: 2024-01-19T18:30:44.948Z
Electron: 25.9.7
ElectronBuildId: undefined
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.7.3-200.fc39.x86_64

**Comment by djacquensf9** [comment]
Do you have this problem only when working on Remote Development?

**Comment by PilarHidalgo** [comment]
his could be due to several reasons. Here are some steps you can take to resolve this:

Update Visual Studio Code to version 1.85 or higher.
Ensure you have Node version 20.0 or higher installed.
Check if the CodeGPT extension version 3.2.5 or higher is running.
If you've checked all these and the issue persists, I recommend visiting the documentation for more detailed troubleshooting steps: https://docs.codegpt.co/docs/intro.
