### ISSUE TITLE
scrolling is very jittery and distracting

### ISSUE THREAD

**Issue by adamb** [davila7/code-gpt-docs#212]
whenever the response is more than a few lines, the codegpt window jitters like crazy.  Is there a way to fix this?  I'm usintg ChatGPT 4 as my provider.

**Comment by PilarHidalgo** [comment]
I'm sorry to hear that you're experiencing issues with the CodeGPT window. This could be due to a variety of factors, including your system's performance or a bug in the extension. Here are a few steps you can try:

Ensure that your Visual Studio Code (VSCode) is updated to the latest version.
Check if your system meets the minimum requirements for running VSCode and the CodeGPT extension.
Try disabling other VSCode extensions to see if there's a conflict causing the issue.
Reinstall the CodeGPT extension.
