### ISSUE TITLE
Custom API Url Need

### ISSUE THREAD

**Issue by kuyin** [davila7/code-gpt-docs#274]
![image](https://github.com/davila7/code-gpt-docs/assets/7321275/23e25195-4cd0-48d2-9e93-93cc873368d3)

**Comment by Adel242** [comment]
Hello, thank you for writing to Code GPT, it is imperative that you please provide us with more information regarding your problem in order to help you. If your question is about how to customize the URL of the Open AI API, the Open AI endpoint cannot be changed, as this is established by the provider.
