### ISSUE TITLE
Incomplete Completion

### ISSUE THREAD

**Issue by perqa** [davila7/code-gpt-docs#34]
When trying to refactor or explain longer chunks of code (350 lines or so), I get the following error message:

`Ops! Incomplete Completion. The request requires 3043 tokens and you only have 500. Add more tokens in your CodeGPT Settings.`

If I open Extension Settings for CodeGPT, it says "No Settings Found". And even if there were settings and I increased the max tokens, there would always be an upper limit. It might be possible to divide the code into smaller chunks, but with refactoring, it doesn't really work to refactor chunk by chunk. You need the full picture before starting. I realise this is mainly a limitation with the ChatGPT API, but is there any way around this issue?

**Comment by davila7** [comment]
This is the big problem with public OpenAI models.
https://platform.openai.com/docs/models/gpt-3

The solution is to wait for OpenAI to release the ChatGPT model (really soon) since that model allows a prompt with many more tokens.

I'm already on the waiting list, so as soon as it's published, we will have it on CodeGPT
