### ISSUE TITLE
History isn't stored - if you leave the chat page and return it's blank.

### ISSUE THREAD

**Issue by dreadedhamish** [davila7/code-gpt-docs#71]
I couldn't find anything in the docs about this.
When I leave the codeGPT page in vscode (by opening the Files tab etc...) and then click on the codeGPT tab again everything is gone. I tried asking chatGPT for it - "show me my chatGPT history" but it returns no results.

**Comment by davila7** [comment]
Precisely, requesting assistance from the VSCode - Microsoft team to help me so that the chat history record does not disappear.
It will be fixed soon

<img width="593" alt="Captura de Pantalla 2023-03-18 a la(s) 1 12 10 p  m" src="https://user-images.githubusercontent.com/6216945/226122282-6d2c7756-fec4-48b9-a5da-b1b8d5eb1084.png">
