### ISSUE TITLE
Every response refuses to stop nauseously scrolling to the bottom with every chunk

### ISSUE THREAD

**Issue by rogadev** [davila7/code-gpt-docs#99]
In regular ChatGPT, when the prompt starts spewing out chunks, a simple flick of the scroll wheel stops the nauseous downward scroll to the bottom of the latest chunk as it appears. In CodeGPT there is no such effect. It's dizzying, irritating, and I absolutely hate it. I totally understand that it's brand new and constantly improving but I felt it was important to let you know that I uninstalled the extension today because I can't deal with visual effect every time I enter a prompt. I do appreciate all the hard work and I think it's a wonderful tool. 🙏 BUT, this was a deal-breaker, for me.

**Comment by davila7** [comment]
Hi @rogadev 
Thanks for reporting the issue. We already found the problem and it will be solved in the next version.

We will continue to improve this free extension with the help of the reports that the community sends us, but we also appreciate the patience and hope that you and the entire community may have so that we can continue to improve Code GPT.

Please use the extension again with this new version (2.1.4) so that you can continue to provide feedback and improvements.
The only way we can have a tool with the same (or better) quality than Github Copilot is through the community.

**Comment by davila7** [comment]
@rogadev 

The new version 2.1.4 is now available
